"""Combine the 4-file split back into a single-file Open WebUI Function/Pipe.

Open WebUI loads a Function as exactly one file, so the split below (convenient
for editing) has to be flattened before upload:

    planning_core.py       - data model, prompts, text/JSON helpers
    planning_kev_mcp.py    - Kev decision client + MCP client
    planning_engine.py     - StandalonePlanner (the agentic loop)
    planning_backends.py   - completion backends, the Open WebUI Pipe, the CLI

This script:
  1. Reads the 4 source files in that (dependency) order.
  2. Uses planning_backends.py's module docstring - it holds the Open WebUI
     frontmatter (title/author/version/required_open_webui_version/description)
     that Open WebUI parses to register the Function - as the combined file's
     docstring, and discards the others.
  3. Collects every top-level `import` / `from X import Y` line, skipping the
     intra-split `from planning_core import ...` / `from planning_kev_mcp import
     ...` / `from planning_engine import ...` lines (meaningless once merged
     into one namespace), dedupes them (first-seen order kept), and emits them
     once, right after the docstring.
  4. Concatenates the remaining body of each file, in order, preserving any
     comments that sit between the import block and the first statement (e.g.
     each file's section banner).

Usage:
    python build_filter.py             # writes planning_standalone.py next to this script
    python build_filter.py -o out.py   # custom output path
    python build_filter.py --check     # build in memory and verify it compiles; don't write
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
from typing import Optional

SOURCES = [
    "planning_core.py",
    "planning_kev_mcp.py",
    "planning_engine.py",
    "planning_backends.py",
]
# Holds the Open WebUI frontmatter (title/author/version/...); becomes the
# combined file's module docstring.
DOCSTRING_SOURCE = "planning_backends.py"


def _is_intra_split_import(node: ast.ImportFrom) -> bool:
    return (node.module or "").startswith("planning_")


def _split_header_body(path: Path) -> tuple[str, list[str], str]:
    """Return (docstring, import_lines, body) for one source file.

    `body` starts right after the last top-level import statement (or the
    docstring, if there are no imports), so comments sitting in that gap - a
    file's section banner, most often - travel with the body instead of being
    silently dropped.
    """
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text, filename=str(path))
    lines = text.splitlines(keepends=True)

    docstring = ast.get_docstring(tree, clean=False) or ""
    import_lines: list[str] = []
    last_header_end: Optional[int] = None

    for index, node in enumerate(tree.body):
        if (
            index == 0
            and isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            last_header_end = node.end_lineno
            continue
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            last_header_end = node.end_lineno
            if isinstance(node, ast.ImportFrom) and _is_intra_split_import(node):
                continue  # drop, but it still counts as part of the header region
            import_lines.append("".join(lines[node.lineno - 1 : node.end_lineno]))
            continue
        break  # first non-docstring, non-import top-level statement: body starts here

    body_start = (last_header_end or 0) + 1
    body = "".join(lines[body_start - 1 :])
    return docstring, import_lines, body


def build() -> str:
    here = Path(__file__).resolve().parent
    docstring = ""
    seen_imports: dict[str, None] = {}
    bodies: list[str] = []

    for name in SOURCES:
        doc, imports, body = _split_header_body(here / name)
        if name == DOCSTRING_SOURCE:
            docstring = doc
        for line in imports:
            stripped = line.rstrip("\n")
            if stripped.strip() == "from __future__ import annotations":
                continue
            seen_imports.setdefault(stripped, None)
        bodies.append(body.strip("\n"))

    parts = [
        f'"""{docstring}"""\n\n',
        "# NOTE: generated by build_filter.py from planning_core.py, planning_kev_mcp.py,\n"
        "# planning_engine.py and planning_backends.py. Edit those, not this file, then\n"
        "# re-run `python build_filter.py` to regenerate it.\n\n",
        "from __future__ import annotations\n\n",
    ]
    parts.extend(line + "\n" for line in seen_imports)
    parts.append("\n\n")
    parts.append("\n\n\n".join(bodies))
    parts.append("\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--out",
        default=None,
        help="Output path (default: planning_standalone.py next to this script)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Build and verify the result compiles; don't write a file",
    )
    args = parser.parse_args()

    combined = build()
    compile(combined, "<planning_standalone.py>", "exec")

    if args.check:
        print(f"OK: combined output compiles cleanly ({combined.count(chr(10))} lines)")
        return 0

    out_path = (
        Path(args.out)
        if args.out
        else Path(__file__).resolve().parent / "planning_standalone.py"
    )
    out_path.write_text(combined, encoding="utf-8")
    print(f"wrote {out_path} ({combined.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
